name: Version Bump Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is merged to main
        id: pr-merged
        run: echo "::set-output name=merged::${{ github.event.pull_request.merged }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Version Bump
        if: steps.pr-merged.outputs.merged == 'true'
        run: |
          # Your version bumping logic here
          # Example: increment the MINOR version
          version=$(cat version.txt)  # Assuming your version is stored in a file
          IFS='.' read -ra parts <<< "$version"
          new_minor=$((parts[1] + 1))
          new_version="${parts[0]}.${new_minor}.${parts[2]}"
          echo "$new_version" > version.txt

          git add version.txt
          git commit -m "Bump MINOR version"
          git push origin main

      - name: Create Version Tag
        if: steps.pr-merged.outputs.merged == 'true'
        run: |
          # Create a Git tag for the new version
          git tag -a v$new_version -m "Version $new_version"
          git push origin v$new_version
